name: "Test job"
description: "Test the package with pytest."
runs:
  using: "composite"
  steps:
    - name: Prepare locales
      run: sudo locale-gen de_DE.UTF-8 en_GB.UTF-8 || echo windows
      shell: bash
    - name: Prepare timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: Europe/Berlin
        timezoneMacos: Europe/Berlin
        timezoneWindows: W. Europe Standard Time
    - name: Print yadg version
      run: yadg --version
      shell: bash
    - name: Run pytest
      run: pytest -vv
      shell: bash
