name: "Test job"
description: "Test the package with pytest."
runs:
  using: "composite"
  steps:
    - name: Prepare locales
      run: sudo locale-gen de_DE.UTF-8 || echo windows
      shell: bash
    - name: Print yadg version
      run: yadg --version
      shell: bash
    - name: Run pytest
      run: pytest -vv
      shell: bash
