"""
This module parses the files generated by the ``dummy`` and ``biologic`` devices
within ``tomato-0.2``. As the ``dummy`` device has been mainly used for testing,
the below discusses the output of a ``biologic`` device.

Usage
`````
Available since ``yadg-4.0``.

.. autopydantic_model:: dgbowl_schemas.yadg.dataschema_6_0.filetype.Tomato_json

Schema
``````
.. code-block:: yaml

    xarray.DataTree:
      coords:
        uts:            !!float     # Unix timestamp
      data_vars:
        Ewe:            (uts)       # Potential of the working electrode
        Ece:            (uts)       # Potential of the counter electrode, if present
        I:              (uts)       # Instantaneous current
        technique:      (uts)       # Technique name
        loop number:    (uts)       # Loop number  (over techniques)
        cycle number:   (uts)       # Cycle number (within technique)
        index:          (uts)       # Technique index


Uncertainties
`````````````
- ``I``: constant uncertainty of 0.0015% FSR up to 0.76 µA, from VMP-3 datasheets
- ``Ewe`` and ``Ece``: constant uncertainty of 0.004% FSR up to 75 µV, from VMP-3 datasheets.

Metadata
````````
No metadata is extracted.

Notes on file structure
```````````````````````
The files generated by the ``dummy`` driver do not contain the ``technique``, and all
values present in the json files are simply copied over assuming an uncertainty of 0.0.

For the ``biologic`` driver, each tomato data file contains the following four sections:

- ``technique`` section, describing the current technique,
- ``previous`` section, containing status information of the previous file,
- ``current`` section, containing status information of the current file,
- ``data`` section, containing the timesteps.

The reason why both ``previous`` and ``current`` are requires is that the device
status is recorded at the time of data polling, which means the values in ``current``
might be invalid (after the run has finished) or not in sync with the ``data`` (if
a technique change happened). However, ``previous`` may not be present in the first
data file of an experiment.


.. codeauthor::
    Peter Kraus

"""

import json
import logging
import xarray as xr
from xarray import DataTree
from yadg import dgutils
from pathlib import Path
from yadg.extractors import get_extract_dispatch

extract = get_extract_dispatch()
logger = logging.getLogger(__name__)

I_ranges = {
    "1 A": 1e0,
    "100 mA": 1e-1,
    "10 mA": 1e-2,
    "1 mA": 1e-3,
    "100 uA": 1e-4,
    "10 uA": 1e-5,
    "1 uA": 1e-6,
    "100 pA": 1e-7,
}


def biologic_tomato_json(fn: Path, jsdata: dict) -> DataTree:
    technique = jsdata["technique"]
    previous = jsdata.get("previous", None)
    current = jsdata["current"]

    if "uts" in technique:
        uts = technique["uts"]
        fulldate = True
    else:
        uts = 0
        fulldate = False

    uts += technique["start_time"]

    if previous is None:
        meta = current
    elif current["status"] == "STOP":
        meta = previous
    elif previous["elapsed_time"] > technique["start_time"]:
        meta = previous
    else:
        meta = current

    I_range = I_ranges[meta["I_range"]]
    E_range = meta["E_range"]["max"] - meta["E_range"]["min"]

    data_vars = {
        "loop number": [],
        "technique": [],
        "index": [],
        "time": [],
        "Ewe": [],
        "Ece": [],
        "I": [],
        "cycle": [],
    }

    E_dev = max(E_range * 0.0015 / 100, 75e-6)
    I_dev = max(I_range * 0.004 / 100, 760e-12)

    for point in jsdata["data"]:
        for k, v in point.items():
            if k == "time":
                data_vars[k].append(uts + v)
            elif k in {"Ewe", "Ece"}:
                data_vars[k].append(v)
            elif k in {"I"}:
                data_vars[k].append(v)
            elif k in {"cycle"}:
                data_vars[k].append(v)
            else:
                logger.cricital(f"parameter {k}: {v} not understood.")
        data_vars["loop number"].append(technique["loop_number"])
        data_vars["technique"].append(technique["name"])
        data_vars["index"].append(technique["index"])

    data_vars["cycle number"] = data_vars.pop("cycle")
    uts = data_vars.pop("time")

    data_vars = {k: v for k, v in data_vars.items() if len(v) > 0}
    keys = list(data_vars.keys())

    for k in keys:
        if k in {"Ewe", "Ece", "I"}:
            ku = f"{k}_uncertainty"
            data_vars[k] = (
                ["uts"],
                data_vars[k],
                {
                    "units": "A" if k == "I" else "V",
                    "ancillary_variables": ku,
                },
            )
            data_vars[ku] = (
                [],
                I_dev if k == "I" else E_dev,
                {
                    "standard_name": f"{k} standard_error",
                    "standard_error_multiplier": 1,
                    "yadg_uncertainty_type": "abs",
                    "yadg_uncertainty_distribution": "rectangular",
                    "yadg_uncertainty_source": "datasheet",
                },
            )
        else:
            data_vars[k] = (["uts"], data_vars[k])

    ds = xr.Dataset(data_vars, coords=dict(uts=uts))
    if not fulldate:
        ds.attrs["fulldate"] = False
    return DataTree(ds)


def dummy_tomato_json(fn: Path, jsdata: dict) -> DataTree:
    data_vals = {}
    meta_vals = {}
    for vi, vals in enumerate(jsdata["data"]):
        vals["uts"] = vals.pop("time")
        dgutils.append_dicts(vals, {}, data_vals, meta_vals, vi)
    return DataTree(dgutils.dicts_to_dataset(data_vals, meta_vals, fulldate=False))


@extract.register(Path)
def extract_from_path(
    source: Path,
    **kwargs: dict,
) -> DataTree:
    with open(source, "r") as inf:
        jsdata = json.load(inf)

    if "technique" in jsdata:
        return biologic_tomato_json(source, jsdata)
    else:
        return dummy_tomato_json(source, jsdata)
