---
name: Build yadg docs
on:
    workflow_call:
        inputs:
            os:
                required: true
                type: string
            pyver:
                required: true
                type: string

jobs:
    pages:
        runs-on: ${{ inputs.os }}
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: ${{ inputs.pyver }}
          - uses: actions/download-artifact@v4
            with:
                name: dist-${{ inputs.os }}-${{ inputs.pyver }}
          - uses: jannekem/run-python-script-action@v1
            with:
                script: |
                    import os
                    import subprocess
                    fn = [f for f in os.listdir() if f.endswith('whl') and f.startswith('yadg')][0]
                    subprocess.run(["pip", "install", f"{fn}[docs]"])
          - name: Build the docs
            shell: bash
            run: |
                sphinx-apidoc -o docs/source/apidoc src/yadg -T -M -f --templatedir=docs/apidoc_t
                sphinx-build -W -b html docs/source public/master
          - uses: actions/upload-artifact@v4
            with:
              name: public-${{ inputs.os }}-${{ inputs.pyver }}
              path: public/master
